### ISSUE TITLE
On Boot menu crashes

### ISSUE THREAD

**Issue by kolAflash** [SmartPack/SmartPack-Kernel-Manager#151]
App Name: SmartPack-Kernel Manager
Package Name: com.smartpack.kernelmanager
App Version: v17.6
SDK Version: 29
OS: [/e/OS](https://en.wikipedia.org/wiki//e/_(operating_system))-1.4q (LineageOS based Android-10)
Device: [Fairphone 3+](https://en.wikipedia.org/wiki/Fairphone_3)

Steps to reproduce the issue: create a script, enable for boot, open "On Boot" menu

Crash Report:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at b4.u.f(SourceFile:3)
	at androidx.recyclerview.widget.RecyclerView$t.i(SourceFile:891)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.G0(SourceFile:4)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.T0(SourceFile:34)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.c0(Unknown Source:1)
	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:39)
	at androidx.recyclerview.widget.RecyclerView.p(SourceFile:91)
	at androidx.recyclerview.widget.RecyclerView.m(SourceFile:142)
	at androidx.recyclerview.widget.RecyclerView$a.run(Unknown Source:31)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by sunilpaulmathew** [comment]
@kolAflash 
Thanks for reporting. It is a well-known bug which need significant work to fix in a proper way.
But there is a workaround: Enable On-Boot on one more section (any section).
