### ISSUE TITLE
Bug: Crashes on launch

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [SmartPack/SmartPack-Kernel-Manager#19]
Backtrace:

```
time: 1565207265821
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
stacktrace: java.lang.ExceptionInInitializerError
	at com.grarak.kerneladiutor.activities.MainActivity.onCreate(:2)
	at android.app.Activity.performCreate(Activity.java:7145)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6739)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at h.b.a.b.<clinit>(Unknown Source:8)
	... 16 more

**Comment by sunilpaulmathew** [comment]
Hi, sorry for the delayed response.
& I need more details (how, when etc.) to solve this issue? Are you sure that the app has root access?

**Comment by TanyaEleventhGoddess** [comment]
It happens on startup

Yes I am sure that the app has root access

**Comment by sunilpaulmathew** [comment]
That's really strange. I never got that issue. Any other details of your device?

**Comment by TanyaEleventhGoddess** [comment]
HavocOS 2.3, android 9
